# Generated by Django 2.1.3 on 2018-12-02 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameFinder', '0002_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('sport', models.CharField(max_length=16)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('Street', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameFinder.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameFinder.Game')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameFinder.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Location_Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(max_length=16)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameFinder.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='GameFinder.User')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='GameFinder.User')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameFinder.User')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_accept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='GameFinder.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='GameFinder.Player'),
        ),
    ]
