# Generated by Django 2.1.3 on 2018-12-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameFinder', '0003_auto_20181202_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='location_request',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='location_request',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='location_sports',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='player',
        ),
    ]
