# Generated by Django 2.1.3 on 2018-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameFinder', '0004_auto_20181202_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='location_request',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
